"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Vehicle_1 = require("./Vehicle");
var VehicleRegistration_1 = require("./VehicleRegistration");
var car1 = new Vehicle_1.default("Auto", "Peugeout", "208", 2023);
var motorcycle1 = new Vehicle_1.default("Moto", "Honda", "CBR1000", 2022);
var truck1 = new Vehicle_1.default("Camion", "Scania", "G340", 2013);
console.log("".concat(car1.getType(), ", ").concat(car1.getBrand(), ", ").concat(car1.getModel(), ", ").concat(car1.getYear()));
car1.setYear(2024);
console.log("Changed year: ".concat(car1.getYear()));
var registration = new VehicleRegistration_1.default();
registration.addVehicle(car1);
registration.addVehicle(motorcycle1);
registration.addVehicle(truck1);
console.log(registration.getVehicles());
registration.deleteVehicle(car1);
console.log(registration.getVehicles());
registration.modifyVehicle(motorcycle1, "year", 2023);
registration.modifyVehicle(motorcycle1, "brand", "Yamaha");
registration.modifyVehicle(motorcycle1, "model", "MT03");
console.log(registration.getVehicles());
